services:
  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./_data/conf.d:/etc/nginx/conf.d"
      - "./certs:/certs"
    networks:
      - nginx
    restart: unless-stopped

networks:
  nginx:
    external: true

